version: 2

builds:
  - main: ./cmd/ndql
    id: ndql
    binary: ndql
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      # - amd64
      - arm64
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w -X github.com/berquerant/ndql/version.Version={{ .Version }} -X github.com/berquerant/ndql/version.Revision={{ .ShortCommit }}

archives:
  - formats: binary
    id: ndql
    files:
      - NOTICE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  use_existing_draft: true
