name: test

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: "false"
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5
      - name: Lint
        run: mise run lint

  test-unit:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: "false"
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5
      - name: Test
        run: mise run test

  govulncheck:
    timeout-minutes: 5
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: berquerant/govulncheck-action@7c7f559180aca72a1badcead05a3d5d81fc95c30 # v1.0.3
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
